### ISSUE TITLE
Why sha256 hash become an issue on release PIN verify function?

### ISSUE THREAD

**Issue by hsinyu-chen** [orsonwang/Taiwan_CDC_RI#1]
can you explain more detail for this?
can't we just hash pin code then send with apdu command?

**Comment by orsonwang** [comment]
Because the spec is locked and owned by CHT.

**Comment by hsinyu-chen** [comment]
A personal company owned a national card's spec. ridiculous

**Comment by orsonwang** [comment]
You can expect if new national ID would be locked into specified vendor or not?!

**Comment by hsinyu-chen** [comment]
base on [this](https://talk.pdis.nat.gov.tw/t/topic/4787/2) I hope not.
but .. 英文不足以表達我心中的幹XX心情，雖然我只是要讀健保卡但我覺得這件事真的狗幹扯。

**Comment by orsonwang** [comment]
Sorry, that's my bad(Typo for years). The password is not SHA256 hashed. It is AES encrypted.

**Comment by orsonwang** [comment]
> base on [this](https://talk.pdis.nat.gov.tw/t/topic/4787/6) I hope not.
> but .. 英文不足以表達我心中的幹XX心情，雖然我只是要讀健保卡但我覺得這件事真的狗幹扯。

NHI Card has no issue on password as it did not have password.

**Comment by hsinyu-chen** [comment]
Yes, I just assume the pin verify is standard command for smart card and search about MOICA card
and I was wrong , I didn't expect the cause is the AES key owned by CHT

**Comment by orsonwang** [comment]
> Yes, I just assume the pin verify is standard command for smart card and search about MOICA card
> and I was wrong , I didn't expect the cause is the AES key owned by CHT

So was I .

**Comment by 0xmerp** [comment]
This is an old topic but since this was posted, someone has released the NHI card agent network authentication protocol, with all necessary encryption keys: https://github.com/Inndy/twnhi-smartcard-agent/blob/master/complicated_sam_hc_auth.py

Without the authentication, the only user-accessible data on the NHI card itself was name, ID, card no, date of birth. It's just a different protocol & type of card (PKCS#11 vs custom network authentication & SAMs)

Anyways, since the NHI release was ok, it seems the PIN verify would've been fine too.

The PKCS#11 interface is standard for certificate smart cards, just the actual APDUs are different.

Btw, CHT was originally a government department many years ago, if it feels like there is some favoritism. Technically anyone can apply (even now) to also offer their own smartcards. But I'd guess those requests are all denied.

**Comment by orson-wang** [comment]
CDC card use a different way from NHI card, there is HCA card on NHI series. As somekind of stakeholder I am. Reverse engine the code was not my option. And it was supposed to be replaced 5 years ago. Just got notify that eID project was officially kickoff today 6 years ago.
